name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/seclook
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Install project and dependencies
        run: uv pip install .

      - name: Install build tool
        run: uv pip install build

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}