name: Release

on:
  workflow_run:
    workflows: ["CD"]
    types: [completed]


jobs:
  release:
    name: Create Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: |
          VERSION=$(cat pyproject.toml | grep version | head -1 | awk -F= '{ print $2 }' | sed 's/[\",]//g' | tr -d '[:space:]')
          echo "Detected version: $VERSION"
          echo "::set-output name=version::${VERSION}"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false